# Generated by Django 4.1.7 on 2023-03-15 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_block_users_of_service', 'Can block users of the service')]},
        ),
    ]
