# Generated by Django 4.1.7 on 2023-03-15 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailingsettings',
            options={'permissions': [('can_disable_mailings', 'Can disable mailings')], 'verbose_name': 'настройка', 'verbose_name_plural': 'настройки'},
        ),
    ]
